# General Settings :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
baseURL = "/"
theme = "terminal"
paginate = 10

# Language Settings ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
languageCode = "en"

# Flags ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
enableEmoji = true
enableRobotsTXT = true

# Labels :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
title = "Digital Poet"
owner = "Digital Poet"
copyright = "Aran Moncusí Ramírez"
