
showLastUpdated = false

# Terminal Theme Params ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

# ["orange", "blue", "red", "green", "pink"]
themeColor = "orange"

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with _default width
centerTheme = false

# Labels :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
keywords = "Aran Moncusí Ramírez, Developer, Devlops, Backend"
menuMore = "Show items"

# Logo Params ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[logo]
logoText = "Digital Poet"
